### ISSUE TITLE
Sucessfully running on RevolutionPi Connect S

### ISSUE THREAD

**Issue by flurin137** [eva-ics/roboplc#1]
Hi Everyone,

I've managed to run RoboPLC on the RevolutionPI Connect S (https://revolutionpi.com/en/revpi-connect).
It runs on the 64Bit Bullseye Debian Light image.

In order to install the RoboPLC Manager on the system, io had to repackage the .deb file using the steps provided in https://unix.stackexchange.com/questions/669004/zst-compression-not-supported-by-apt-dpkg/745467#745467 since Debian Bullseye comes by default with a dpkg version without support for zstd. After the repackaging. Everything seems to work correctly.

Keep up the good work! Thanks

**Comment by divi255** [comment]
Thanks for the kind feedback. I'll take a look into Bullseye and try repacking further debs with no zstd compression, it's not mandatory for us.

**Comment by divi255** [comment]
also note that for the legacy systems certain function might not work (e.g. channel sending/receiving with timeout) when using priority-inherited locking. the minimum recommended kernel for real-time safe is now 5.14

**Comment by divi255** [comment]
the roboplc manager debs 0.4.4+ are forcibly packed with xz now

**Comment by flurin137** [comment]
Thanks for the hint on the kernel version. It seems that the kernel is in fact `Linux 6.1.46-rt13-v8 aarch64` even if the version of the distro is `Debian GNU/Linux 11 (bullseye)`.
